#!/bin/sh
#
# chrx
#
# A wrapper for chrx-install

: ${CHRX_WEB_ROOT:="https://chrx.org"}
CHRX_CACHE0_DIR="/var/tmp/chrx"
CHRX_LOG_FILE="${CHRX_CACHE0_DIR}/chrx-install.log"

# Silence sudo message
sudo -v >/dev/null 2>&1

# Error handling for commands
if [ $? -ne 0 ]; then
    echo "Error: Failed to run sudo command."
    exit 1
fi

rm -rf "${CHRX_CACHE0_DIR}"
mkdir -p "${CHRX_CACHE0_DIR}" || { echo "Error: Failed to create directory."; exit 1; }
cd "${CHRX_CACHE0_DIR}" || { echo "Error: Failed to change directory."; exit 1; }

echo "## $0 $@" > "$CHRX_LOG_FILE"

# Need sudo -E to keep exported environment variables
(
export CHRX_WEB_ROOT CHRX_CACHE0_DIR
#curl -Os "${CHRX_WEB_ROOT}/chrx-install" && sudo -E bash ./chrx-install "$@"
sudo -E /usr/local/bin/chrx-install "$@"
) 2>&1 | tee -a "${CHRX_LOG_FILE}"

# Log file will be copied to chroot by install-chrx.
# Can't copy here -- partition is unmounted when we get back.

# Get stderr into tee: bash: `|& tee`; sh: `2>&1 | tee`
